// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/organization/common.proto

package organization

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultStatus int32

const (
	ResultStatus_Success     ResultStatus = 0
	ResultStatus_MaxLimit    ResultStatus = 1
	ResultStatus_Repeated    ResultStatus = 2
	ResultStatus_NotExisted  ResultStatus = 3
	ResultStatus_DBException ResultStatus = 4
	ResultStatus_Empty       ResultStatus = 5
)

var ResultStatus_name = map[int32]string{
	0: "Success",
	1: "MaxLimit",
	2: "Repeated",
	3: "NotExisted",
	4: "DBException",
	5: "Empty",
}

var ResultStatus_value = map[string]int32{
	"Success":     0,
	"MaxLimit":    1,
	"Repeated":    2,
	"NotExisted":  3,
	"DBException": 4,
	"Empty":       5,
}

func (x ResultStatus) String() string {
	return proto.EnumName(ResultStatus_name, int32(x))
}

func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{0}
}

type AddressInfo struct {
	Country              string   `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Province             string   `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Location             string   `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressInfo) Reset()         { *m = AddressInfo{} }
func (m *AddressInfo) String() string { return proto.CompactTextString(m) }
func (*AddressInfo) ProtoMessage()    {}
func (*AddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{0}
}

func (m *AddressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressInfo.Unmarshal(m, b)
}
func (m *AddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressInfo.Marshal(b, m, deterministic)
}
func (m *AddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressInfo.Merge(m, src)
}
func (m *AddressInfo) XXX_Size() int {
	return xxx_messageInfo_AddressInfo.Size(m)
}
func (m *AddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddressInfo proto.InternalMessageInfo

func (m *AddressInfo) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AddressInfo) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *AddressInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddressInfo) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *AddressInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type PairInfo struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairInfo) Reset()         { *m = PairInfo{} }
func (m *PairInfo) String() string { return proto.CompactTextString(m) }
func (*PairInfo) ProtoMessage()    {}
func (*PairInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{1}
}

func (m *PairInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairInfo.Unmarshal(m, b)
}
func (m *PairInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairInfo.Marshal(b, m, deterministic)
}
func (m *PairInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairInfo.Merge(m, src)
}
func (m *PairInfo) XXX_Size() int {
	return xxx_messageInfo_PairInfo.Size(m)
}
func (m *PairInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PairInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PairInfo proto.InternalMessageInfo

func (m *PairInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PairInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AreaInfo struct {
	Id                   uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string      `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              uint64      `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64      `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string      `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string      `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string      `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string      `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Parent               string      `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	Template             string      `protobuf:"bytes,11,opt,name=template,proto3" json:"template,omitempty"`
	Device               string      `protobuf:"bytes,12,opt,name=device,proto3" json:"device,omitempty"`
	Question             string      `protobuf:"bytes,13,opt,name=question,proto3" json:"question,omitempty"`
	Type                 uint32      `protobuf:"varint,14,opt,name=type,proto3" json:"type,omitempty"`
	Catalog              string      `protobuf:"bytes,15,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Sn                   string      `protobuf:"bytes,16,opt,name=sn,proto3" json:"sn,omitempty"`
	Aspect               string      `protobuf:"bytes,17,opt,name=aspect,proto3" json:"aspect,omitempty"`
	Limit                uint32      `protobuf:"varint,18,opt,name=limit,proto3" json:"limit,omitempty"`
	Displays             []string    `protobuf:"bytes,21,rep,name=displays,proto3" json:"displays,omitempty"`
	Terminal             *DeviceInfo `protobuf:"bytes,25,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Modules              []*PairInfo `protobuf:"bytes,31,rep,name=modules,proto3" json:"modules,omitempty"`
	Sources              []*PairInfo `protobuf:"bytes,32,rep,name=sources,proto3" json:"sources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AreaInfo) Reset()         { *m = AreaInfo{} }
func (m *AreaInfo) String() string { return proto.CompactTextString(m) }
func (*AreaInfo) ProtoMessage()    {}
func (*AreaInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{2}
}

func (m *AreaInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaInfo.Unmarshal(m, b)
}
func (m *AreaInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaInfo.Marshal(b, m, deterministic)
}
func (m *AreaInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaInfo.Merge(m, src)
}
func (m *AreaInfo) XXX_Size() int {
	return xxx_messageInfo_AreaInfo.Size(m)
}
func (m *AreaInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AreaInfo proto.InternalMessageInfo

func (m *AreaInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AreaInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AreaInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AreaInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AreaInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AreaInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AreaInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *AreaInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AreaInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *AreaInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *AreaInfo) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *AreaInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *AreaInfo) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *AreaInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AreaInfo) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *AreaInfo) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *AreaInfo) GetAspect() string {
	if m != nil {
		return m.Aspect
	}
	return ""
}

func (m *AreaInfo) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AreaInfo) GetDisplays() []string {
	if m != nil {
		return m.Displays
	}
	return nil
}

func (m *AreaInfo) GetTerminal() *DeviceInfo {
	if m != nil {
		return m.Terminal
	}
	return nil
}

func (m *AreaInfo) GetModules() []*PairInfo {
	if m != nil {
		return m.Modules
	}
	return nil
}

func (m *AreaInfo) GetSources() []*PairInfo {
	if m != nil {
		return m.Sources
	}
	return nil
}

type DeviceInfo struct {
	Id                   uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string    `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              uint64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string    `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string    `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Remark               string    `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	Owner                string    `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Sn                   string    `protobuf:"bytes,10,opt,name=sn,proto3" json:"sn,omitempty"`
	Quote                string    `protobuf:"bytes,11,opt,name=quote,proto3" json:"quote,omitempty"`
	Os                   string    `protobuf:"bytes,12,opt,name=os,proto3" json:"os,omitempty"`
	Expiry               uint32    `protobuf:"varint,13,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Certificate          string    `protobuf:"bytes,14,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Type                 uint32    `protobuf:"varint,15,opt,name=type,proto3" json:"type,omitempty"`
	Activated            int64     `protobuf:"varint,16,opt,name=activated,proto3" json:"activated,omitempty"`
	Status               uint32    `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	Meta                 string    `protobuf:"bytes,18,opt,name=meta,proto3" json:"meta,omitempty"`
	Auto                 *PairInfo `protobuf:"bytes,19,opt,name=auto,proto3" json:"auto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeviceInfo) Reset()         { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()    {}
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{3}
}

func (m *DeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceInfo.Unmarshal(m, b)
}
func (m *DeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceInfo.Marshal(b, m, deterministic)
}
func (m *DeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfo.Merge(m, src)
}
func (m *DeviceInfo) XXX_Size() int {
	return xxx_messageInfo_DeviceInfo.Size(m)
}
func (m *DeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfo proto.InternalMessageInfo

func (m *DeviceInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeviceInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *DeviceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *DeviceInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *DeviceInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *DeviceInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *DeviceInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *DeviceInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DeviceInfo) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *DeviceInfo) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func (m *DeviceInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *DeviceInfo) GetExpiry() uint32 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *DeviceInfo) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *DeviceInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *DeviceInfo) GetActivated() int64 {
	if m != nil {
		return m.Activated
	}
	return 0
}

func (m *DeviceInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeviceInfo) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *DeviceInfo) GetAuto() *PairInfo {
	if m != nil {
		return m.Auto
	}
	return nil
}

type RequestInfo struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Flag                 uint32   `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{4}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestInfo) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type RequestPage struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Number               uint32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPage) Reset()         { *m = RequestPage{} }
func (m *RequestPage) String() string { return proto.CompactTextString(m) }
func (*RequestPage) ProtoMessage()    {}
func (*RequestPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{5}
}

func (m *RequestPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPage.Unmarshal(m, b)
}
func (m *RequestPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPage.Marshal(b, m, deterministic)
}
func (m *RequestPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPage.Merge(m, src)
}
func (m *RequestPage) XXX_Size() int {
	return xxx_messageInfo_RequestPage.Size(m)
}
func (m *RequestPage) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPage.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPage proto.InternalMessageInfo

func (m *RequestPage) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *RequestPage) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type RequestFilter struct {
	Scene                string   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32   `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	Flag                 uint32   `protobuf:"varint,7,opt,name=flag,proto3" json:"flag,omitempty"`
	List                 []string `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFilter) Reset()         { *m = RequestFilter{} }
func (m *RequestFilter) String() string { return proto.CompactTextString(m) }
func (*RequestFilter) ProtoMessage()    {}
func (*RequestFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{6}
}

func (m *RequestFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFilter.Unmarshal(m, b)
}
func (m *RequestFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFilter.Marshal(b, m, deterministic)
}
func (m *RequestFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFilter.Merge(m, src)
}
func (m *RequestFilter) XXX_Size() int {
	return xxx_messageInfo_RequestFilter.Size(m)
}
func (m *RequestFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFilter.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFilter proto.InternalMessageInfo

func (m *RequestFilter) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *RequestFilter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RequestFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestFilter) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestFilter) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestFilter) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *RequestFilter) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqUpdateFilter struct {
	Scene                string   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Values               []string `protobuf:"bytes,6,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdateFilter) Reset()         { *m = ReqUpdateFilter{} }
func (m *ReqUpdateFilter) String() string { return proto.CompactTextString(m) }
func (*ReqUpdateFilter) ProtoMessage()    {}
func (*ReqUpdateFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{7}
}

func (m *ReqUpdateFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdateFilter.Unmarshal(m, b)
}
func (m *ReqUpdateFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdateFilter.Marshal(b, m, deterministic)
}
func (m *ReqUpdateFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdateFilter.Merge(m, src)
}
func (m *ReqUpdateFilter) XXX_Size() int {
	return xxx_messageInfo_ReqUpdateFilter.Size(m)
}
func (m *ReqUpdateFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdateFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdateFilter proto.InternalMessageInfo

func (m *ReqUpdateFilter) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqUpdateFilter) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqUpdateFilter) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqUpdateFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ReqUpdateFilter) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqUpdateFilter) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type ReplyStatus struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{8}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplyStatus) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ReplyInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{9}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RequestAddress struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Province             string   `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Zone                 string   `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Location             string   `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestAddress) Reset()         { *m = RequestAddress{} }
func (m *RequestAddress) String() string { return proto.CompactTextString(m) }
func (*RequestAddress) ProtoMessage()    {}
func (*RequestAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{10}
}

func (m *RequestAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestAddress.Unmarshal(m, b)
}
func (m *RequestAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestAddress.Marshal(b, m, deterministic)
}
func (m *RequestAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestAddress.Merge(m, src)
}
func (m *RequestAddress) XXX_Size() int {
	return xxx_messageInfo_RequestAddress.Size(m)
}
func (m *RequestAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestAddress.DiscardUnknown(m)
}

var xxx_messageInfo_RequestAddress proto.InternalMessageInfo

func (m *RequestAddress) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestAddress) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *RequestAddress) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *RequestAddress) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *RequestAddress) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *RequestAddress) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *RequestAddress) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestFlag struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Flag                 string   `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestFlag) Reset()         { *m = RequestFlag{} }
func (m *RequestFlag) String() string { return proto.CompactTextString(m) }
func (*RequestFlag) ProtoMessage()    {}
func (*RequestFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{11}
}

func (m *RequestFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestFlag.Unmarshal(m, b)
}
func (m *RequestFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestFlag.Marshal(b, m, deterministic)
}
func (m *RequestFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestFlag.Merge(m, src)
}
func (m *RequestFlag) XXX_Size() int {
	return xxx_messageInfo_RequestFlag.Size(m)
}
func (m *RequestFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestFlag.DiscardUnknown(m)
}

var xxx_messageInfo_RequestFlag proto.InternalMessageInfo

func (m *RequestFlag) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestFlag) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *RequestFlag) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestList struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []string `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestList) Reset()         { *m = RequestList{} }
func (m *RequestList) String() string { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()    {}
func (*RequestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{12}
}

func (m *RequestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestList.Unmarshal(m, b)
}
func (m *RequestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestList.Marshal(b, m, deterministic)
}
func (m *RequestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestList.Merge(m, src)
}
func (m *RequestList) XXX_Size() int {
	return xxx_messageInfo_RequestList.Size(m)
}
func (m *RequestList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestList proto.InternalMessageInfo

func (m *RequestList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestList) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyList struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	List                 []string     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyList) Reset()         { *m = ReplyList{} }
func (m *ReplyList) String() string { return proto.CompactTextString(m) }
func (*ReplyList) ProtoMessage()    {}
func (*ReplyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{13}
}

func (m *ReplyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyList.Unmarshal(m, b)
}
func (m *ReplyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyList.Marshal(b, m, deterministic)
}
func (m *ReplyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyList.Merge(m, src)
}
func (m *ReplyList) XXX_Size() int {
	return xxx_messageInfo_ReplyList.Size(m)
}
func (m *ReplyList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyList proto.InternalMessageInfo

func (m *ReplyList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyStatistic struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Key                  string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Owner                string       `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Count                uint32       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStatistic) Reset()         { *m = ReplyStatistic{} }
func (m *ReplyStatistic) String() string { return proto.CompactTextString(m) }
func (*ReplyStatistic) ProtoMessage()    {}
func (*ReplyStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b563812ef86dc2c, []int{14}
}

func (m *ReplyStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatistic.Unmarshal(m, b)
}
func (m *ReplyStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatistic.Marshal(b, m, deterministic)
}
func (m *ReplyStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatistic.Merge(m, src)
}
func (m *ReplyStatistic) XXX_Size() int {
	return xxx_messageInfo_ReplyStatistic.Size(m)
}
func (m *ReplyStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatistic proto.InternalMessageInfo

func (m *ReplyStatistic) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStatistic) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReplyStatistic) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReplyStatistic) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("omo.msp.scene.ResultStatus", ResultStatus_name, ResultStatus_value)
	proto.RegisterType((*AddressInfo)(nil), "omo.msp.scene.AddressInfo")
	proto.RegisterType((*PairInfo)(nil), "omo.msp.scene.PairInfo")
	proto.RegisterType((*AreaInfo)(nil), "omo.msp.scene.AreaInfo")
	proto.RegisterType((*DeviceInfo)(nil), "omo.msp.scene.DeviceInfo")
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.scene.RequestInfo")
	proto.RegisterType((*RequestPage)(nil), "omo.msp.scene.RequestPage")
	proto.RegisterType((*RequestFilter)(nil), "omo.msp.scene.RequestFilter")
	proto.RegisterType((*ReqUpdateFilter)(nil), "omo.msp.scene.ReqUpdateFilter")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.scene.ReplyStatus")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.scene.ReplyInfo")
	proto.RegisterType((*RequestAddress)(nil), "omo.msp.scene.RequestAddress")
	proto.RegisterType((*RequestFlag)(nil), "omo.msp.scene.RequestFlag")
	proto.RegisterType((*RequestList)(nil), "omo.msp.scene.RequestList")
	proto.RegisterType((*ReplyList)(nil), "omo.msp.scene.ReplyList")
	proto.RegisterType((*ReplyStatistic)(nil), "omo.msp.scene.ReplyStatistic")
}

func init() {
	proto.RegisterFile("proto/organization/common.proto", fileDescriptor_5b563812ef86dc2c)
}

var fileDescriptor_5b563812ef86dc2c = []byte{
	// 987 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xcd, 0x8e, 0xdc, 0x44,
	0x10, 0xc6, 0x7f, 0xf3, 0xd3, 0xb3, 0x9e, 0x1d, 0xcc, 0x12, 0x3a, 0x11, 0x52, 0x46, 0x3e, 0xad,
	0x40, 0x9a, 0x88, 0x45, 0x88, 0x73, 0xa2, 0x6c, 0x24, 0xa4, 0x00, 0x89, 0x23, 0x2e, 0xdc, 0x3a,
	0x76, 0xef, 0xa8, 0x15, 0xdb, 0xed, 0xed, 0x6e, 0x2f, 0x3b, 0x39, 0x72, 0xe1, 0x09, 0x78, 0x00,
	0xde, 0x82, 0x17, 0xe1, 0x11, 0x78, 0x0f, 0x54, 0xd5, 0x6d, 0x8f, 0x77, 0x7e, 0x92, 0x3d, 0x73,
	0xab, 0xaf, 0xdd, 0x55, 0xf5, 0x55, 0xd7, 0xd7, 0x5d, 0x26, 0x8f, 0x1b, 0x25, 0x8d, 0x7c, 0x22,
	0xd5, 0x9a, 0xd5, 0xe2, 0x3d, 0x33, 0x42, 0xd6, 0x4f, 0x72, 0x59, 0x55, 0xb2, 0x5e, 0xe1, 0x97,
	0x24, 0x96, 0x95, 0x5c, 0x55, 0xba, 0x59, 0xe9, 0x9c, 0xd7, 0x3c, 0xfd, 0xc3, 0x23, 0xb3, 0xa7,
	0x45, 0xa1, 0xb8, 0xd6, 0x3f, 0xd4, 0x57, 0x32, 0xa1, 0x64, 0x9c, 0xcb, 0xb6, 0x36, 0x6a, 0x43,
	0xbd, 0xa5, 0x77, 0x3e, 0xcd, 0x3a, 0x98, 0x3c, 0x22, 0x93, 0x46, 0xc9, 0x1b, 0x51, 0xe7, 0x9c,
	0xfa, 0xf8, 0xa9, 0xc7, 0x49, 0x42, 0xc2, 0x5c, 0x98, 0x0d, 0x0d, 0x70, 0x1d, 0x6d, 0x58, 0x7b,
	0x2f, 0x6b, 0x4e, 0x43, 0xbb, 0x06, 0x36, 0xc4, 0x28, 0x65, 0x8e, 0xac, 0x68, 0x64, 0x63, 0x74,
	0x38, 0xbd, 0x20, 0x93, 0x57, 0x4c, 0x28, 0x64, 0xb1, 0x20, 0xc1, 0x3b, 0xde, 0x31, 0x00, 0x33,
	0x39, 0x23, 0xd1, 0x0d, 0x2b, 0xdb, 0x2e, 0xb5, 0x05, 0xe9, 0xbf, 0x21, 0x99, 0x3c, 0x55, 0x9c,
	0xa1, 0xd3, 0x9c, 0xf8, 0xa2, 0x40, 0x9f, 0x30, 0xf3, 0x45, 0x01, 0x41, 0x5a, 0x51, 0x38, 0x07,
	0x30, 0x81, 0x52, 0xcd, 0x2a, 0xde, 0xd1, 0x04, 0x1b, 0x0b, 0x56, 0x9c, 0x19, 0x5e, 0x20, 0xd3,
	0x30, 0xeb, 0x20, 0x7c, 0x69, 0x9b, 0x02, 0xbf, 0x44, 0xf6, 0x8b, 0x83, 0xbd, 0x8f, 0x54, 0x74,
	0xe4, 0x0e, 0xc9, 0x42, 0x28, 0x50, 0x36, 0x5c, 0xe1, 0xa7, 0xb1, 0x2d, 0xb0, 0xc3, 0xc9, 0x03,
	0x32, 0x52, 0xbc, 0x62, 0xea, 0x1d, 0x9d, 0xe0, 0x17, 0x87, 0xa0, 0x34, 0xf9, 0x5b, 0xcd, 0x15,
	0x9d, 0xda, 0xd2, 0x10, 0xc0, 0xee, 0x86, 0x29, 0x5e, 0x1b, 0x4a, 0xec, 0x6e, 0x8b, 0x20, 0x83,
	0xe1, 0x55, 0x53, 0x32, 0xc3, 0xe9, 0xcc, 0x66, 0xe8, 0x30, 0xf8, 0x14, 0xfc, 0x46, 0xe4, 0x9c,
	0x9e, 0x58, 0x1f, 0x8b, 0xc0, 0xe7, 0xba, 0xe5, 0x1a, 0x8f, 0x3d, 0xb6, 0x3e, 0x1d, 0x86, 0x33,
	0x31, 0x9b, 0x86, 0xd3, 0xf9, 0xd2, 0x3b, 0x8f, 0x33, 0xb4, 0xb1, 0x3e, 0x66, 0x58, 0x29, 0xd7,
	0xf4, 0xd4, 0xd5, 0x67, 0x21, 0x9c, 0xb1, 0xae, 0xe9, 0x02, 0x17, 0x7d, 0x5d, 0x43, 0x46, 0xa6,
	0x1b, 0x9e, 0x1b, 0xfa, 0xa9, 0xcd, 0x68, 0x11, 0xd4, 0x54, 0x8a, 0x4a, 0x18, 0x9a, 0x60, 0x58,
	0x0b, 0x80, 0x47, 0x21, 0x74, 0x53, 0xb2, 0x8d, 0xa6, 0x9f, 0x2f, 0x03, 0xe0, 0xd1, 0xe1, 0xe4,
	0x3b, 0xa8, 0x4b, 0x55, 0xa2, 0x66, 0x25, 0x7d, 0xb8, 0xf4, 0xce, 0x67, 0x17, 0x0f, 0x57, 0x77,
	0xa4, 0xba, 0x7a, 0x8e, 0xc5, 0x40, 0xab, 0xb3, 0x7e, 0x6b, 0xf2, 0x0d, 0x19, 0x57, 0xb2, 0x68,
	0x4b, 0xae, 0xe9, 0xe3, 0x65, 0x70, 0x3e, 0xbb, 0xf8, 0x62, 0xc7, 0xab, 0xd3, 0x54, 0xd6, 0xed,
	0x03, 0x17, 0x2d, 0x5b, 0x95, 0x73, 0x4d, 0x97, 0x1f, 0x71, 0x71, 0xfb, 0xd2, 0x7f, 0x02, 0x42,
	0xb6, 0xe9, 0xff, 0x67, 0x4a, 0xb3, 0x3d, 0x25, 0x7d, 0x4f, 0xcf, 0x48, 0x74, 0xdd, 0xca, 0x5e,
	0x5e, 0x16, 0xc0, 0x2e, 0xa9, 0x9d, 0xae, 0x7c, 0xa9, 0x21, 0x07, 0xbf, 0x6d, 0x84, 0xda, 0xa0,
	0xa2, 0xe2, 0xcc, 0xa1, 0x64, 0x49, 0x66, 0x39, 0x57, 0x46, 0x5c, 0x89, 0x1c, 0x24, 0x3a, 0x47,
	0x87, 0xe1, 0x52, 0xaf, 0xb8, 0xd3, 0x81, 0xe2, 0xbe, 0x24, 0x53, 0x96, 0x1b, 0x71, 0x83, 0x67,
	0x00, 0xf2, 0x0a, 0xb2, 0xed, 0x02, 0xe4, 0xd2, 0x86, 0x99, 0x56, 0xa3, 0xca, 0xe2, 0xcc, 0x21,
	0x88, 0x54, 0x71, 0xc3, 0x50, 0x64, 0xd3, 0x0c, 0xed, 0xe4, 0x6b, 0x12, 0xb2, 0xd6, 0x48, 0xfa,
	0x19, 0x6a, 0xe8, 0x68, 0x6b, 0x71, 0x53, 0xba, 0x26, 0xb3, 0x8c, 0xe3, 0x55, 0xc0, 0xbe, 0x6e,
	0xef, 0x9c, 0x77, 0xe7, 0xce, 0xed, 0xf7, 0x77, 0x78, 0xfa, 0xc1, 0xce, 0xe9, 0x27, 0x24, 0xbc,
	0x2a, 0xd9, 0x1a, 0x9b, 0x1c, 0x67, 0x68, 0xa7, 0xaf, 0xfb, 0x44, 0xaf, 0xd8, 0x9a, 0x1f, 0x4d,
	0xf4, 0x80, 0x8c, 0xea, 0xb6, 0x7a, 0xcb, 0x15, 0xe6, 0x8a, 0x33, 0x87, 0x20, 0x64, 0xc3, 0xd6,
	0x56, 0x4e, 0x71, 0x86, 0x76, 0xfa, 0x97, 0x47, 0x62, 0x17, 0xf3, 0x85, 0x28, 0x0d, 0x57, 0xd0,
	0x38, 0xac, 0xd2, 0x05, 0xb5, 0xa0, 0x7b, 0x4b, 0xfd, 0x03, 0x6f, 0x69, 0x30, 0x78, 0x4b, 0xfb,
	0x1c, 0xe1, 0x36, 0xc7, 0x80, 0x4f, 0xb4, 0xcb, 0x07, 0x4b, 0x1c, 0x6f, 0x4b, 0x84, 0xb5, 0x52,
	0x68, 0x43, 0x47, 0x78, 0xb1, 0xd1, 0x4e, 0xff, 0xf4, 0xc8, 0x69, 0xc6, 0xaf, 0x7f, 0x41, 0x35,
	0x7f, 0x8c, 0xe5, 0xce, 0x11, 0x3b, 0xde, 0xc1, 0x01, 0xde, 0xe1, 0x90, 0xf7, 0xb0, 0x15, 0xd1,
	0xfe, 0x45, 0xc0, 0x4d, 0xda, 0xb1, 0x72, 0x28, 0xfd, 0x1e, 0xda, 0xd1, 0x94, 0x9b, 0x37, 0xbd,
	0x8e, 0x72, 0x59, 0x58, 0x46, 0x71, 0x86, 0x36, 0x24, 0xe3, 0x4a, 0x49, 0xd5, 0x0d, 0x1c, 0x04,
	0xe9, 0x6b, 0x32, 0x45, 0xc7, 0x6e, 0x4a, 0xb5, 0xee, 0x1d, 0x70, 0x9c, 0x2f, 0x7a, 0xa1, 0xfa,
	0x28, 0xbf, 0x47, 0x3b, 0xf2, 0x1b, 0x24, 0xed, 0x44, 0x9c, 0xfe, 0xed, 0x91, 0xb9, 0xeb, 0xa3,
	0x1b, 0xc4, 0x07, 0x02, 0x0f, 0xc6, 0xb2, 0x7f, 0x7c, 0x2c, 0x07, 0x47, 0xc6, 0x72, 0x78, 0x60,
	0x2c, 0x47, 0x47, 0xc6, 0xf2, 0xe8, 0xee, 0x58, 0xfe, 0xd0, 0x3b, 0x93, 0xfe, 0xdc, 0xab, 0xfa,
	0x05, 0x28, 0x60, 0x9f, 0x76, 0xa7, 0x13, 0xcb, 0xd9, 0xea, 0xe4, 0x03, 0x57, 0x67, 0x10, 0xf0,
	0xa5, 0xd0, 0xe6, 0x40, 0xc0, 0xa1, 0xb3, 0xbf, 0x7f, 0xef, 0x50, 0x80, 0xc1, 0x40, 0x80, 0xdc,
	0xf5, 0xeb, 0x48, 0xb8, 0xce, 0xc5, 0xdf, 0xba, 0x0c, 0x7a, 0x18, 0xdc, 0xbb, 0x87, 0xbf, 0x63,
	0x0f, 0xdd, 0xba, 0xd0, 0x46, 0xe4, 0x83, 0x30, 0xde, 0x7d, 0xc3, 0x1c, 0xbe, 0xaa, 0xf6, 0xc5,
	0x0e, 0x86, 0x2f, 0xf6, 0x19, 0x89, 0xb0, 0xfd, 0xee, 0xae, 0x5a, 0xf0, 0x55, 0x4e, 0x4e, 0x32,
	0xae, 0xdb, 0xd2, 0x38, 0x55, 0xcf, 0xc8, 0xf8, 0x4d, 0x9b, 0xe7, 0x5c, 0xeb, 0xc5, 0x27, 0xc9,
	0x09, 0x99, 0xfc, 0xc8, 0x6e, 0x5f, 0xc2, 0x18, 0x5e, 0x78, 0x80, 0x32, 0xde, 0xe0, 0xf0, 0x59,
	0xf8, 0xc9, 0x9c, 0x90, 0x9f, 0xa4, 0xb9, 0xbc, 0x15, 0x1a, 0x70, 0x90, 0x9c, 0x92, 0xd9, 0xf3,
	0x67, 0x97, 0xb7, 0x39, 0x6f, 0x40, 0x01, 0x8b, 0x30, 0x99, 0x92, 0xe8, 0xb2, 0x6a, 0xcc, 0x66,
	0x11, 0x3d, 0x3b, 0xfb, 0x35, 0xd9, 0xff, 0xc3, 0x7c, 0x3b, 0xc2, 0xb5, 0x6f, 0xff, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0xf3, 0x95, 0xc4, 0x7e, 0x0a, 0x00, 0x00,
}
