// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/organization/maintain.proto

package organization

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MaintainInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Device               string   `protobuf:"bytes,8,opt,name=device,proto3" json:"device,omitempty"`
	Scene                string   `protobuf:"bytes,9,opt,name=scene,proto3" json:"scene,omitempty"`
	Date                 string   `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	Area                 string   `protobuf:"bytes,11,opt,name=area,proto3" json:"area,omitempty"`
	Submitter            string   `protobuf:"bytes,12,opt,name=submitter,proto3" json:"submitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaintainInfo) Reset()         { *m = MaintainInfo{} }
func (m *MaintainInfo) String() string { return proto.CompactTextString(m) }
func (*MaintainInfo) ProtoMessage()    {}
func (*MaintainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_22b76e010cb7bf06, []int{0}
}

func (m *MaintainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaintainInfo.Unmarshal(m, b)
}
func (m *MaintainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaintainInfo.Marshal(b, m, deterministic)
}
func (m *MaintainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintainInfo.Merge(m, src)
}
func (m *MaintainInfo) XXX_Size() int {
	return xxx_messageInfo_MaintainInfo.Size(m)
}
func (m *MaintainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MaintainInfo proto.InternalMessageInfo

func (m *MaintainInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *MaintainInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MaintainInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MaintainInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *MaintainInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MaintainInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MaintainInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *MaintainInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *MaintainInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *MaintainInfo) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *MaintainInfo) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *MaintainInfo) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

type ReqMaintainAdd struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Scene                string   `protobuf:"bytes,4,opt,name=scene,proto3" json:"scene,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Date                 string   `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Area                 string   `protobuf:"bytes,8,opt,name=area,proto3" json:"area,omitempty"`
	Submitter            string   `protobuf:"bytes,9,opt,name=submitter,proto3" json:"submitter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMaintainAdd) Reset()         { *m = ReqMaintainAdd{} }
func (m *ReqMaintainAdd) String() string { return proto.CompactTextString(m) }
func (*ReqMaintainAdd) ProtoMessage()    {}
func (*ReqMaintainAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_22b76e010cb7bf06, []int{1}
}

func (m *ReqMaintainAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMaintainAdd.Unmarshal(m, b)
}
func (m *ReqMaintainAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMaintainAdd.Marshal(b, m, deterministic)
}
func (m *ReqMaintainAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMaintainAdd.Merge(m, src)
}
func (m *ReqMaintainAdd) XXX_Size() int {
	return xxx_messageInfo_ReqMaintainAdd.Size(m)
}
func (m *ReqMaintainAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMaintainAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMaintainAdd proto.InternalMessageInfo

func (m *ReqMaintainAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqMaintainAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqMaintainAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqMaintainAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqMaintainAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqMaintainAdd) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ReqMaintainAdd) GetArea() string {
	if m != nil {
		return m.Area
	}
	return ""
}

func (m *ReqMaintainAdd) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

type ReplyMaintainInfo struct {
	Status               *ReplyStatus  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *MaintainInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyMaintainInfo) Reset()         { *m = ReplyMaintainInfo{} }
func (m *ReplyMaintainInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyMaintainInfo) ProtoMessage()    {}
func (*ReplyMaintainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_22b76e010cb7bf06, []int{2}
}

func (m *ReplyMaintainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMaintainInfo.Unmarshal(m, b)
}
func (m *ReplyMaintainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMaintainInfo.Marshal(b, m, deterministic)
}
func (m *ReplyMaintainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMaintainInfo.Merge(m, src)
}
func (m *ReplyMaintainInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyMaintainInfo.Size(m)
}
func (m *ReplyMaintainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMaintainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMaintainInfo proto.InternalMessageInfo

func (m *ReplyMaintainInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyMaintainInfo) GetInfo() *MaintainInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyMaintainList struct {
	Status               *ReplyStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                uint32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32          `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32          `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32          `protobuf:"varint,5,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*MaintainInfo `protobuf:"bytes,16,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyMaintainList) Reset()         { *m = ReplyMaintainList{} }
func (m *ReplyMaintainList) String() string { return proto.CompactTextString(m) }
func (*ReplyMaintainList) ProtoMessage()    {}
func (*ReplyMaintainList) Descriptor() ([]byte, []int) {
	return fileDescriptor_22b76e010cb7bf06, []int{3}
}

func (m *ReplyMaintainList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMaintainList.Unmarshal(m, b)
}
func (m *ReplyMaintainList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMaintainList.Marshal(b, m, deterministic)
}
func (m *ReplyMaintainList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMaintainList.Merge(m, src)
}
func (m *ReplyMaintainList) XXX_Size() int {
	return xxx_messageInfo_ReplyMaintainList.Size(m)
}
func (m *ReplyMaintainList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMaintainList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMaintainList proto.InternalMessageInfo

func (m *ReplyMaintainList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyMaintainList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyMaintainList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyMaintainList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyMaintainList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyMaintainList) GetList() []*MaintainInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*MaintainInfo)(nil), "omo.msp.scene.MaintainInfo")
	proto.RegisterType((*ReqMaintainAdd)(nil), "omo.msp.scene.ReqMaintainAdd")
	proto.RegisterType((*ReplyMaintainInfo)(nil), "omo.msp.scene.ReplyMaintainInfo")
	proto.RegisterType((*ReplyMaintainList)(nil), "omo.msp.scene.ReplyMaintainList")
}

func init() {
	proto.RegisterFile("proto/organization/maintain.proto", fileDescriptor_22b76e010cb7bf06)
}

var fileDescriptor_22b76e010cb7bf06 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xfa, 0x91, 0xb6, 0xb7, 0x1f, 0x0c, 0xab, 0x42, 0x56, 0xd9, 0x20, 0xe4, 0xa9, 0x4f,
	0xad, 0x54, 0x7e, 0xc1, 0x86, 0x44, 0x41, 0x6c, 0x9a, 0xe4, 0x89, 0x17, 0xde, 0xdc, 0xe6, 0x6e,
	0xb2, 0x68, 0xe2, 0xcc, 0x71, 0x27, 0xca, 0x2f, 0xe1, 0x27, 0xf1, 0xc8, 0x3b, 0x7f, 0x06, 0xd9,
	0x4e, 0x43, 0x3f, 0xb2, 0x15, 0xf1, 0x76, 0xcf, 0xc9, 0xf5, 0xf1, 0x3d, 0xe7, 0x5a, 0x81, 0x37,
	0xa9, 0x92, 0x5a, 0x4e, 0xa4, 0xba, 0xe3, 0x89, 0xf8, 0xce, 0xb5, 0x90, 0xc9, 0x24, 0xe6, 0x22,
	0xd1, 0x5c, 0x24, 0x63, 0xfb, 0x8d, 0xf4, 0x64, 0x2c, 0xc7, 0x71, 0x96, 0x8e, 0xb3, 0x05, 0x26,
	0x38, 0x7c, 0x5d, 0x72, 0x62, 0x21, 0xe3, 0x58, 0xe6, 0xfd, 0xe1, 0x8f, 0x2a, 0x74, 0xaf, 0x72,
	0x89, 0x8f, 0xc9, 0xad, 0x24, 0x27, 0x50, 0x5b, 0x89, 0x88, 0x7a, 0x81, 0x37, 0x6a, 0x33, 0x53,
	0x92, 0x3e, 0x54, 0x45, 0x44, 0xab, 0x81, 0x37, 0xaa, 0xb3, 0xaa, 0x88, 0x08, 0x81, 0xba, 0x5e,
	0xa7, 0x48, 0x6b, 0x81, 0x37, 0xea, 0x31, 0x5b, 0x13, 0x0a, 0xcd, 0x85, 0x42, 0xae, 0x31, 0xa2,
	0xf5, 0xc0, 0x1b, 0xd5, 0xd8, 0x06, 0x16, 0x5f, 0xa4, 0xa2, 0x0d, 0xab, 0xb9, 0x81, 0x46, 0x27,
	0xe1, 0x31, 0x52, 0xdf, 0xd2, 0xb6, 0x26, 0x2f, 0xc0, 0x57, 0x18, 0x73, 0xf5, 0x95, 0x36, 0x2d,
	0x9b, 0x23, 0xc3, 0x47, 0xf8, 0x20, 0x16, 0x48, 0x5b, 0x8e, 0x77, 0x88, 0x0c, 0xa0, 0x61, 0x8d,
	0xd2, 0xb6, 0xa5, 0x1d, 0x30, 0xca, 0x11, 0xd7, 0x48, 0xc1, 0x29, 0x9b, 0xda, 0x70, 0x5c, 0x21,
	0xa7, 0x1d, 0xc7, 0x99, 0x9a, 0x9c, 0x42, 0x3b, 0x5b, 0xcd, 0x63, 0xa1, 0x35, 0x2a, 0xda, 0xb5,
	0x1f, 0xfe, 0x12, 0xe1, 0x4f, 0x0f, 0xfa, 0x0c, 0xef, 0x37, 0xe9, 0x9c, 0x47, 0x51, 0x31, 0xb2,
	0x57, 0x3a, 0x72, 0x75, 0x67, 0xe4, 0xb2, 0x98, 0x8a, 0x71, 0xeb, 0xdb, 0xe3, 0x0e, 0xa1, 0x25,
	0x53, 0x54, 0x5b, 0x19, 0x15, 0xb8, 0xb0, 0xd2, 0x2c, 0xb1, 0xd2, 0x7a, 0xcc, 0x4a, 0x7b, 0xdf,
	0xca, 0x37, 0x78, 0xce, 0x30, 0x5d, 0xae, 0x77, 0x36, 0x3d, 0x05, 0x3f, 0xd3, 0x5c, 0xaf, 0x32,
	0x6b, 0xa7, 0x33, 0x1d, 0x8e, 0x77, 0xde, 0xce, 0xd8, 0x9e, 0xb8, 0xb1, 0x1d, 0x2c, 0xef, 0x24,
	0x13, 0xa8, 0x8b, 0xe4, 0x56, 0x5a, 0xab, 0x9d, 0xe9, 0xcb, 0xbd, 0x13, 0xdb, 0xf2, 0xcc, 0x36,
	0x86, 0xbf, 0xbc, 0xbd, 0xab, 0x2f, 0x45, 0xa6, 0xff, 0xeb, 0xea, 0x01, 0x34, 0xb4, 0xd4, 0x7c,
	0x69, 0xef, 0xee, 0x31, 0x07, 0x0c, 0x9b, 0xf2, 0x3b, 0xcc, 0xf2, 0x98, 0x1d, 0x30, 0x09, 0x99,
	0xc2, 0xc6, 0xdc, 0x63, 0xb6, 0x36, 0x7b, 0x4a, 0x56, 0xf1, 0x1c, 0x5d, 0xc6, 0x3d, 0x96, 0x23,
	0x63, 0x69, 0x29, 0x32, 0x4d, 0x4f, 0x82, 0xda, 0x51, 0x4b, 0xa6, 0x71, 0xfa, 0xbb, 0x06, 0xcf,
	0x36, 0xf4, 0x0d, 0x2a, 0xfb, 0x0e, 0x3f, 0x81, 0x7f, 0x1e, 0x45, 0xd7, 0x09, 0x92, 0xb3, 0x03,
	0x2b, 0xdb, 0x2f, 0x68, 0x18, 0x94, 0x39, 0xdd, 0xbe, 0x24, 0xac, 0x90, 0x0f, 0xe0, 0xcf, 0x50,
	0x1b, 0xb1, 0xc3, 0x5c, 0xee, 0x57, 0x98, 0x69, 0xd3, 0xf7, 0x4f, 0x4a, 0xd7, 0xd0, 0x99, 0xa1,
	0xbe, 0x58, 0xbf, 0x17, 0x4b, 0x8d, 0x8a, 0x9c, 0x96, 0xcb, 0xb9, 0xaf, 0x4f, 0x0b, 0x9a, 0xb5,
	0x85, 0x15, 0x72, 0x05, 0xdd, 0x19, 0x6a, 0xb3, 0x19, 0x91, 0x69, 0xb1, 0x38, 0xa2, 0x78, 0xf6,
	0xd8, 0x5a, 0xed, 0xe1, 0xb0, 0x42, 0x2e, 0xa1, 0xff, 0x39, 0x35, 0x6f, 0xba, 0x18, 0xf1, 0xd5,
	0xa1, 0xa0, 0xeb, 0xc8, 0x25, 0x69, 0x99, 0x64, 0xee, 0xf6, 0x1d, 0xb4, 0x19, 0xc6, 0xf2, 0x01,
	0x8f, 0x45, 0xf7, 0x84, 0xc8, 0xc5, 0xe0, 0x0b, 0x39, 0xfc, 0x67, 0xce, 0x7d, 0xcb, 0xbd, 0xfd,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xfa, 0x7b, 0x47, 0x82, 0x05, 0x00, 0x00,
}
