// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/organization/room.proto

package organization

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomInfo struct {
	Uid                  string         `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64         `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              int64          `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64          `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string         `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string         `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string         `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string         `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Quotes               []string       `protobuf:"bytes,10,rep,name=quotes,proto3" json:"quotes,omitempty"`
	Devices              []*ProductInfo `protobuf:"bytes,11,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{0}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RoomInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoomInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *RoomInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *RoomInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *RoomInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RoomInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *RoomInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *RoomInfo) GetQuotes() []string {
	if m != nil {
		return m.Quotes
	}
	return nil
}

func (m *RoomInfo) GetDevices() []*ProductInfo {
	if m != nil {
		return m.Devices
	}
	return nil
}

type RoomDisplay struct {
	Room                 string   `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Sn                   string   `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Showing              bool     `protobuf:"varint,4,opt,name=showing,proto3" json:"showing,omitempty"`
	List                 []string `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomDisplay) Reset()         { *m = RoomDisplay{} }
func (m *RoomDisplay) String() string { return proto.CompactTextString(m) }
func (*RoomDisplay) ProtoMessage()    {}
func (*RoomDisplay) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{1}
}

func (m *RoomDisplay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDisplay.Unmarshal(m, b)
}
func (m *RoomDisplay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDisplay.Marshal(b, m, deterministic)
}
func (m *RoomDisplay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDisplay.Merge(m, src)
}
func (m *RoomDisplay) XXX_Size() int {
	return xxx_messageInfo_RoomDisplay.Size(m)
}
func (m *RoomDisplay) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDisplay.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDisplay proto.InternalMessageInfo

func (m *RoomDisplay) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *RoomDisplay) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *RoomDisplay) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *RoomDisplay) GetShowing() bool {
	if m != nil {
		return m.Showing
	}
	return false
}

func (m *RoomDisplay) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqRoomAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoomAdd) Reset()         { *m = ReqRoomAdd{} }
func (m *ReqRoomAdd) String() string { return proto.CompactTextString(m) }
func (*ReqRoomAdd) ProtoMessage()    {}
func (*ReqRoomAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{2}
}

func (m *ReqRoomAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoomAdd.Unmarshal(m, b)
}
func (m *ReqRoomAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoomAdd.Marshal(b, m, deterministic)
}
func (m *ReqRoomAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoomAdd.Merge(m, src)
}
func (m *ReqRoomAdd) XXX_Size() int {
	return xxx_messageInfo_ReqRoomAdd.Size(m)
}
func (m *ReqRoomAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoomAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoomAdd proto.InternalMessageInfo

func (m *ReqRoomAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqRoomAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqRoomAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqRoomAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqRoomUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoomUpdate) Reset()         { *m = ReqRoomUpdate{} }
func (m *ReqRoomUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqRoomUpdate) ProtoMessage()    {}
func (*ReqRoomUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{3}
}

func (m *ReqRoomUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoomUpdate.Unmarshal(m, b)
}
func (m *ReqRoomUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoomUpdate.Marshal(b, m, deterministic)
}
func (m *ReqRoomUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoomUpdate.Merge(m, src)
}
func (m *ReqRoomUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqRoomUpdate.Size(m)
}
func (m *ReqRoomUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoomUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoomUpdate proto.InternalMessageInfo

func (m *ReqRoomUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqRoomUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqRoomUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqRoomUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqRoomQuotes struct {
	Scene                string   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Room                 string   `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []string `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoomQuotes) Reset()         { *m = ReqRoomQuotes{} }
func (m *ReqRoomQuotes) String() string { return proto.CompactTextString(m) }
func (*ReqRoomQuotes) ProtoMessage()    {}
func (*ReqRoomQuotes) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{4}
}

func (m *ReqRoomQuotes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoomQuotes.Unmarshal(m, b)
}
func (m *ReqRoomQuotes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoomQuotes.Marshal(b, m, deterministic)
}
func (m *ReqRoomQuotes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoomQuotes.Merge(m, src)
}
func (m *ReqRoomQuotes) XXX_Size() int {
	return xxx_messageInfo_ReqRoomQuotes.Size(m)
}
func (m *ReqRoomQuotes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoomQuotes.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoomQuotes proto.InternalMessageInfo

func (m *ReqRoomQuotes) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqRoomQuotes) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *ReqRoomQuotes) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRoomQuotes) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqRoomDisplays struct {
	Scene                string         `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Operator             string         `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Rooms                []*RoomDisplay `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReqRoomDisplays) Reset()         { *m = ReqRoomDisplays{} }
func (m *ReqRoomDisplays) String() string { return proto.CompactTextString(m) }
func (*ReqRoomDisplays) ProtoMessage()    {}
func (*ReqRoomDisplays) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{5}
}

func (m *ReqRoomDisplays) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoomDisplays.Unmarshal(m, b)
}
func (m *ReqRoomDisplays) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoomDisplays.Marshal(b, m, deterministic)
}
func (m *ReqRoomDisplays) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoomDisplays.Merge(m, src)
}
func (m *ReqRoomDisplays) XXX_Size() int {
	return xxx_messageInfo_ReqRoomDisplays.Size(m)
}
func (m *ReqRoomDisplays) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoomDisplays.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoomDisplays proto.InternalMessageInfo

func (m *ReqRoomDisplays) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqRoomDisplays) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRoomDisplays) GetRooms() []*RoomDisplay {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type ReqRoomDevice struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Device               string   `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoomDevice) Reset()         { *m = ReqRoomDevice{} }
func (m *ReqRoomDevice) String() string { return proto.CompactTextString(m) }
func (*ReqRoomDevice) ProtoMessage()    {}
func (*ReqRoomDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{6}
}

func (m *ReqRoomDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoomDevice.Unmarshal(m, b)
}
func (m *ReqRoomDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoomDevice.Marshal(b, m, deterministic)
}
func (m *ReqRoomDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoomDevice.Merge(m, src)
}
func (m *ReqRoomDevice) XXX_Size() int {
	return xxx_messageInfo_ReqRoomDevice.Size(m)
}
func (m *ReqRoomDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoomDevice.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoomDevice proto.InternalMessageInfo

func (m *ReqRoomDevice) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqRoomDevice) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqRoomDevice) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *ReqRoomDevice) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqRoomDevice) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type ReplyRoomDevices struct {
	Status               *ReplyStatus   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*ProductInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyRoomDevices) Reset()         { *m = ReplyRoomDevices{} }
func (m *ReplyRoomDevices) String() string { return proto.CompactTextString(m) }
func (*ReplyRoomDevices) ProtoMessage()    {}
func (*ReplyRoomDevices) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{7}
}

func (m *ReplyRoomDevices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRoomDevices.Unmarshal(m, b)
}
func (m *ReplyRoomDevices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRoomDevices.Marshal(b, m, deterministic)
}
func (m *ReplyRoomDevices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRoomDevices.Merge(m, src)
}
func (m *ReplyRoomDevices) XXX_Size() int {
	return xxx_messageInfo_ReplyRoomDevices.Size(m)
}
func (m *ReplyRoomDevices) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRoomDevices.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRoomDevices proto.InternalMessageInfo

func (m *ReplyRoomDevices) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRoomDevices) GetList() []*ProductInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyRoomInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *RoomInfo    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyRoomInfo) Reset()         { *m = ReplyRoomInfo{} }
func (m *ReplyRoomInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyRoomInfo) ProtoMessage()    {}
func (*ReplyRoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{8}
}

func (m *ReplyRoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRoomInfo.Unmarshal(m, b)
}
func (m *ReplyRoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRoomInfo.Marshal(b, m, deterministic)
}
func (m *ReplyRoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRoomInfo.Merge(m, src)
}
func (m *ReplyRoomInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyRoomInfo.Size(m)
}
func (m *ReplyRoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRoomInfo proto.InternalMessageInfo

func (m *ReplyRoomInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRoomInfo) GetInfo() *RoomInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyRoomList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*RoomInfo  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyRoomList) Reset()         { *m = ReplyRoomList{} }
func (m *ReplyRoomList) String() string { return proto.CompactTextString(m) }
func (*ReplyRoomList) ProtoMessage()    {}
func (*ReplyRoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_002834448c4f3442, []int{9}
}

func (m *ReplyRoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyRoomList.Unmarshal(m, b)
}
func (m *ReplyRoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyRoomList.Marshal(b, m, deterministic)
}
func (m *ReplyRoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyRoomList.Merge(m, src)
}
func (m *ReplyRoomList) XXX_Size() int {
	return xxx_messageInfo_ReplyRoomList.Size(m)
}
func (m *ReplyRoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyRoomList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyRoomList proto.InternalMessageInfo

func (m *ReplyRoomList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyRoomList) GetList() []*RoomInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*RoomInfo)(nil), "omo.msp.scene.RoomInfo")
	proto.RegisterType((*RoomDisplay)(nil), "omo.msp.scene.RoomDisplay")
	proto.RegisterType((*ReqRoomAdd)(nil), "omo.msp.scene.ReqRoomAdd")
	proto.RegisterType((*ReqRoomUpdate)(nil), "omo.msp.scene.ReqRoomUpdate")
	proto.RegisterType((*ReqRoomQuotes)(nil), "omo.msp.scene.ReqRoomQuotes")
	proto.RegisterType((*ReqRoomDisplays)(nil), "omo.msp.scene.ReqRoomDisplays")
	proto.RegisterType((*ReqRoomDevice)(nil), "omo.msp.scene.ReqRoomDevice")
	proto.RegisterType((*ReplyRoomDevices)(nil), "omo.msp.scene.ReplyRoomDevices")
	proto.RegisterType((*ReplyRoomInfo)(nil), "omo.msp.scene.ReplyRoomInfo")
	proto.RegisterType((*ReplyRoomList)(nil), "omo.msp.scene.ReplyRoomList")
}

func init() {
	proto.RegisterFile("proto/organization/room.proto", fileDescriptor_002834448c4f3442)
}

var fileDescriptor_002834448c4f3442 = []byte{
	// 730 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdf, 0x4f, 0xdb, 0x30,
	0x10, 0xc7, 0xdb, 0xa4, 0x3f, 0xaf, 0xc0, 0x90, 0x85, 0x58, 0x56, 0xc1, 0xa8, 0xf2, 0x54, 0x69,
	0x52, 0x99, 0xba, 0xfd, 0x03, 0xfc, 0x10, 0xdd, 0x24, 0x26, 0x46, 0xd0, 0x5e, 0xf6, 0x16, 0x1a,
	0xc3, 0xbc, 0x35, 0x71, 0xb0, 0x1d, 0x10, 0x7b, 0xdb, 0x3f, 0xb3, 0xff, 0x71, 0x6f, 0x93, 0xcf,
	0x4e, 0x49, 0x21, 0x69, 0x25, 0xc4, 0x9b, 0xcf, 0x77, 0xf9, 0xde, 0xdd, 0xe7, 0x6c, 0x2b, 0xb0,
	0x9b, 0x0a, 0xae, 0xf8, 0x3e, 0x17, 0xd7, 0x61, 0xc2, 0x7e, 0x87, 0x8a, 0xf1, 0x64, 0x5f, 0x70,
	0x1e, 0x8f, 0x70, 0x9f, 0xac, 0xf3, 0x98, 0x8f, 0x62, 0x99, 0x8e, 0xe4, 0x94, 0x26, 0xb4, 0xbf,
	0x57, 0x12, 0x3d, 0xe5, 0x71, 0xcc, 0x13, 0x13, 0xef, 0xff, 0x75, 0xa0, 0x13, 0x70, 0x1e, 0x7f,
	0x4e, 0xae, 0x38, 0xd9, 0x04, 0x37, 0x63, 0x91, 0x57, 0x1f, 0xd4, 0x87, 0xdd, 0x40, 0x2f, 0xc9,
	0x06, 0x38, 0x2c, 0xf2, 0x9c, 0x41, 0x7d, 0xd8, 0x08, 0x1c, 0x16, 0x11, 0x02, 0x8d, 0x24, 0x8c,
	0xa9, 0xe7, 0x62, 0x08, 0xae, 0x89, 0x07, 0xed, 0xa9, 0xa0, 0xa1, 0xa2, 0x91, 0xd7, 0x18, 0xd4,
	0x87, 0x6e, 0x90, 0x9b, 0xda, 0x93, 0xa5, 0x11, 0x7a, 0x9a, 0xc6, 0x63, 0xcd, 0xf9, 0x37, 0x5c,
	0x78, 0x2d, 0x94, 0xca, 0x4d, 0xd2, 0x87, 0x0e, 0x4f, 0xa9, 0x40, 0x57, 0x1b, 0x5d, 0x73, 0x9b,
	0x6c, 0x41, 0x93, 0xdf, 0x25, 0x54, 0x78, 0x1d, 0x74, 0x18, 0x83, 0x6c, 0x43, 0x4b, 0xd0, 0x38,
	0x14, 0xbf, 0xbc, 0x2e, 0x6e, 0x5b, 0x4b, 0xef, 0xdf, 0x64, 0x5c, 0x51, 0xe9, 0xc1, 0xc0, 0xd5,
	0xfb, 0xc6, 0x22, 0x1f, 0xa1, 0x1d, 0xd1, 0x5b, 0x36, 0xa5, 0xd2, 0xeb, 0x0d, 0xdc, 0x61, 0x6f,
	0xdc, 0x1f, 0x2d, 0x40, 0x1b, 0x7d, 0x15, 0x3c, 0xca, 0xa6, 0x4a, 0x23, 0x09, 0xf2, 0x50, 0x3f,
	0x83, 0x9e, 0xe6, 0x74, 0xcc, 0x64, 0x3a, 0x0b, 0xef, 0x35, 0x08, 0x4d, 0xdd, 0xb2, 0xc2, 0xb5,
	0x86, 0x25, 0x13, 0x84, 0xd5, 0x0d, 0x1c, 0x99, 0xe8, 0x72, 0xaf, 0x05, 0xcf, 0x52, 0x4b, 0xcb,
	0x18, 0xba, 0x75, 0xf9, 0x83, 0xdf, 0xb1, 0xe4, 0x1a, 0x71, 0x75, 0x82, 0xdc, 0xd4, 0x9a, 0x33,
	0x26, 0x95, 0xd7, 0xc4, 0x72, 0x71, 0xed, 0xff, 0x04, 0x08, 0xe8, 0x8d, 0xce, 0x7c, 0x10, 0x45,
	0x0f, 0x00, 0xea, 0x45, 0x00, 0xf9, 0x50, 0x9c, 0xc2, 0x50, 0x1e, 0xa0, 0xb8, 0x0b, 0x50, 0x8a,
	0x78, 0x1b, 0x8b, 0x78, 0x7d, 0x06, 0xeb, 0x36, 0xd7, 0x37, 0x1c, 0x53, 0xc9, 0x79, 0x78, 0xf9,
	0x54, 0xe7, 0x66, 0x28, 0x5b, 0xd0, 0x44, 0xf8, 0x79, 0x67, 0x68, 0xcc, 0x29, 0x3b, 0x05, 0xca,
	0x45, 0x59, 0xf7, 0xd1, 0x01, 0xc9, 0x09, 0x36, 0x0a, 0x04, 0x33, 0x78, 0x65, 0x53, 0xd9, 0xd9,
	0x55, 0x25, 0x2b, 0x0a, 0x3b, 0x8f, 0x84, 0xdf, 0x43, 0x53, 0x27, 0x97, 0x9e, 0x5b, 0x7a, 0x62,
	0x0a, 0xea, 0x81, 0x09, 0xf4, 0xff, 0xd4, 0xe7, 0x2d, 0x1e, 0xe3, 0x11, 0x2a, 0xa1, 0xb9, 0x2c,
	0xe3, 0x36, 0xb4, 0xcc, 0xd1, 0xcb, 0xa9, 0x1a, 0x4b, 0xb7, 0xa8, 0xee, 0x53, 0x8a, 0x44, 0xd7,
	0x03, 0x5c, 0x17, 0x26, 0xd0, 0x2c, 0x4e, 0xc0, 0xbf, 0x85, 0xcd, 0x80, 0xa6, 0xb3, 0xfb, 0x87,
	0x22, 0x24, 0x19, 0x43, 0x4b, 0xaa, 0x50, 0x65, 0x12, 0x0b, 0x29, 0x69, 0x45, 0x7f, 0x70, 0x81,
	0x11, 0x81, 0x8d, 0x24, 0x23, 0x8b, 0xd5, 0x59, 0x79, 0x5d, 0x0c, 0xf2, 0x54, 0xb7, 0x6e, 0xf3,
	0xe2, 0xc3, 0xf2, 0x9c, 0xa4, 0xef, 0xa0, 0xc1, 0x92, 0x2b, 0x8e, 0x60, 0x7a, 0xe3, 0xd7, 0x25,
	0xc4, 0x4d, 0x46, 0x1d, 0xb4, 0x90, 0xf1, 0x94, 0x49, 0xf5, 0xdc, 0x8c, 0x85, 0x36, 0xab, 0x33,
	0xea, 0xa0, 0xf1, 0xbf, 0xa6, 0x79, 0x10, 0x2e, 0xa8, 0xc0, 0xb9, 0x1c, 0x41, 0xeb, 0x20, 0x8a,
	0xce, 0x12, 0x4a, 0xde, 0x3c, 0x49, 0x95, 0xdf, 0xdf, 0xfe, 0x4e, 0x59, 0x15, 0xb9, 0xb0, 0x5f,
	0x23, 0x27, 0x00, 0xe6, 0xea, 0x1d, 0x86, 0x92, 0x92, 0x9d, 0x72, 0x21, 0x13, 0xd1, 0xf7, 0xca,
	0xb4, 0xac, 0xce, 0x11, 0x74, 0x03, 0x1a, 0xf3, 0x5b, 0xaa, 0xeb, 0x79, 0xda, 0xfa, 0x4d, 0x46,
	0x25, 0xce, 0x6b, 0xa9, 0xc8, 0x31, 0xb4, 0x26, 0x54, 0xad, 0x52, 0x58, 0xd5, 0xd2, 0x04, 0xda,
	0x13, 0xaa, 0x70, 0x26, 0x3b, 0xe5, 0x32, 0x27, 0x6c, 0xa6, 0xa8, 0xa8, 0x16, 0xd2, 0xdf, 0xfa,
	0x35, 0xf2, 0x05, 0xd6, 0x26, 0x54, 0xe9, 0x91, 0x31, 0xa9, 0xd8, 0x74, 0x85, 0xda, 0x6e, 0xd5,
	0xbc, 0xf1, 0x63, 0xbf, 0x46, 0xce, 0x60, 0xed, 0x20, 0x4d, 0x69, 0x12, 0xd9, 0xdb, 0x59, 0x01,
	0xdb, 0x78, 0xfb, 0x7b, 0x55, 0xc5, 0xd9, 0x6b, 0xe5, 0xd7, 0xc8, 0x39, 0x6c, 0x5c, 0x64, 0x97,
	0x4a, 0x84, 0x53, 0xf5, 0x52, 0x92, 0x9f, 0x60, 0xcd, 0x0c, 0xdb, 0x3e, 0x92, 0x15, 0x82, 0xc6,
	0xbb, 0x74, 0x96, 0xa7, 0xb0, 0x61, 0x94, 0xe6, 0x6f, 0xe0, 0xdb, 0x8a, 0xe2, 0xac, 0x7f, 0x99,
	0xda, 0xe1, 0xd6, 0x77, 0xf2, 0xf4, 0xbf, 0xe2, 0xb2, 0x85, 0x7b, 0x1f, 0xfe, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x87, 0x24, 0x40, 0x4e, 0xa2, 0x08, 0x00, 0x00,
}
